
name: "Duino coin miner Add-On"
description: "Mine DUCO in Home Assistant"
version: "1.1.2"
slug: "duco-miner"
init: false
arch:
  - aarch64
  - amd64
  - armv7

apparmor: true
backup: hot
tmpfs: true
stage: deprecated

options:
  username: "username"
  mining_key: "None"
schema:
  username: str
  mining_key: str
